--1)
SELECT  COUNT(*) AS ROW_COUNT
  FROM  A_OUT_M
  WHERE brand_cd = 1001
    AND OUT_TYPE_DIV LIKE 'M1%';
  
  
--2)
SELECT  COUNT(*) AS ROW_COUNT
  FROM  A_OUT_M
  WHERE OUTBOUND_DATE BETWEEN '2023-01-02' AND '2023-01-04'
    AND OUT_TYPE_DIV IN ('M11','M21');
  
  
  
--3)
SELECT  BRAND_CD,SUM(ORDER_QTY) AS SUM_QTY
  FROM  A_OUT_D
  WHERE ITEM_CD IN ('A', 'B', 'C')
    AND NOT MOD(ORDER_QTY,2)=0 
  GROUP BY BRAND_CD
  ORDER BY SUM(ORDER_QTY);
  
  
--4)
SELECT  ITEM_CD,SUM(ORDER_QTY) AS SUM_QTY
  FROM  A_OUT_D
  WHERE ORDER_QTY >= 2
  GROUP BY ITEM_CD
 HAVING SUM(ORDER_QTY) > 5
  ORDER BY ITEM_CD;
  
  
--5)
SELECT  BRAND_CD,COUNT(*) AS SUM_QTY
  FROM  A_OUT_D
  WHERE ORDER_QTY BETWEEN 2 AND 5
  GROUP BY BRAND_CD
  ORDER BY COUNT(*);
  
  

  
  
  
  
  
  
  
  
  
  
  
  